ingress:
  host: docs.qameta.io
  path: /allure-report/?(.*)
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^([^.]*[^/])$ $1/ permanent;
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod

  tls:
    - hosts:
        - docs.qameta.io
      secretName: docs-qameta-io-tls

image:
  pullPolicy: Always
  pullSecret: docker-github
  repository: ghcr.io/allure-framework/allure-docs
 