= Allure Documentation

This repository powers docs.qameta.io, which includes documentation for the
https://github.com/allure-framework[Allure Framework].

== Getting started

`./gradlew asciidoctor`

Documentation will be generated in the `build/docs/html5/{version}/index.html` path.

== Style Requirements

=== AsciiDoc
All of our documentation is written in http://asciidoctor.org[AsciiDoctor]. If you're not a Markdown expert but you
have content to contribute, feel free to submit a PR and we'll help you out with the formatting.

=== Writing Style
In general, we try to keep our writing style approachable and easy to understand.

== Contributing
Allure's documentation is open source. We strongly encourage (and value!) any contributions from the community.

Contributions include:
* General content improvement: typo fixes and sentence clarifications
* New content: documentation for new features and guides for common use cases

Please feel free to open an issue or a pull request. See the Contributing Guide for more information.

== Guide for docs-team

First of all create/select the issue you wish to work on. You can use waffle board for that https://waffle.io/allure-framework/allure2?source=allure-framework%2Fallure-docs

Then create a branch (no need to fork the repo!) using the following name convention `{issue-number}-some-comment`, eg `10-jenkins`:

```bash
$ git checkout -b 10-jenkins
$ git push -u origin 10-jenkins
```

After that issue will automatically be assigned to you and moved to `in progress` tab. Then you can commit your work and send a pull request with changes (e.g. using https://github.com/github/hub[hub] util like this):

```bash
$ git commit -am "some awesome changes"
$ git push origin 10-jenkins
$ hub pull-request
```
Note: your pull request message should necessarily contain a line **"fixes #*github issue number*"**, in order to make waffle link your pull request to the issue. 

Then the issue will automatically be moved to `on review` tab.

That is it, at this point we will review it and merge.
