= Allure Documentation

This repository powers docs.qameta.io, which includes documentation for the
https://github.com/allure-framework[Allure Framework].

== Getting started

`./gradlew asciidoctor`

Documentation will be generated in the `build/docs/html5/{version}/index.html` path.

=== Style Requirements

==== AsciiDoc
All of our documentation is written in http://asciidoctor.org[AsciiDoctor]. If you're not a Markdown expert but you
have content to contribute, feel free to submit a PR and we'll help you out with the formatting.

==== Writing Style
In general, we try to keep our writing style approachable and easy to understand.

== Contributing
Allure's documentation is open source. We strongly encourage (and value!) any contributions from the community.

Contributions include:
* General content improvement: typo fixes and sentence clarifications
* New content: documentation for new features and guides for common use cases

Please feel free to open an issue or a pull request. See the Contributing Guide for more information.