= Cucumber JVM

== Allure Cucumber-JVM Adaptor (JUnit)
This adaptor allows to generate allure xml reports after cucumber-jvm Junit test execution.

=== Example project
Example project is located at: https://github.com/allure-examples/allure-cucumber-jvm-example

== Installation

=== Maven
Simply add `allure-allure-cucumber-jvm-adaptor` as dependency to your project and add `build` section
 with adaptor listener:

[source, xml]
----
<project>
...
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-cucumber-jvm-adaptor</artifactId>
            <version>1.5.1</version>
        </dependency>
    </dependencies>
        <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>false</testFailureIgnore>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                    </argLine>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>ru.yandex.qatools.allure.cucumberjvm.AllureRunListener</value>
                        </property>
                    </properties>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>1.7.4</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
----

Then execute `mvn clean test` goal. After tests executed allure xml files will be
placed in `target/allure-results/` directory

== Features
This adapter provides runtime integration allowing conversion of Gherkin dsl features into basic Allure features

=== Title
Titles for tests and suites are extracted at runtime from  `.feature` files

=== Description
WARNING: Description specifications are not supported

=== Steps
WARNING: Allure @Step annotations are not supported, cucumber steps are used as is.

=== Attachments
An attachment in Java code is simply a method annotated with *@Attachment* that returns either
a **String** or **byte[]**, which should be added to the report. You can call this method from
the one of the `Given`/`When`/`Then` step methods.

[source, java]
----
@Attachment
public String performedActions(ActionSequence actionSequence) {
    return actionSequence.toString();
}

@Attachment(value = "Page screenshot", type = "image/png")
public byte[] saveScreenshot(byte[] screenShot) {
    return screenShot;
}
----

If return type in a method annotated with *@Attachment* differs from *String* or *byte[]* we call *toString()*
on return value to get attachment contents.

You can specify exact MIME type for each attached file using *type* parameter of *@Attachment* annotation
like shown above. However there's no need to explicitly specify attachment type for all attached files as Allure
by default analyses attachment contents and can determine attachment type automatically. You usually need to
specify attachment type when working with plain text files.

=== Issues Tracker
WARNING: Bug tracker integration is not supported

=== Test Management System
WARNING: Test management system is not supported

=== Parameters
WARNING: Additional annotations for parameters are not supported

=== Severity
WARNING: Severity annotations are not supported

=== Behaviours Mapping
In some development approaches tests are classified by
https://github.com/allure-framework/allure-core/wiki/Glossary#user-story[stories]
and https://github.com/allure-framework/allure-core/wiki/Glossary#feature[features].
Allure report for cucumber jvm uses information extracted from `Feature:` section