= Commandline
Using Allure command line tool you can generate the report from existing Allure results.

== Installation
Allure CLI is a Java application so it's available for all platforms. You have to manually install Java 1.8 before using Allure CLI

=== Mac OS
You can install Allure CLI via http://brew.sh[Homebrew].

[source,bash]
----
$ brew tap qameta/allure
$ brew install allure
----

After installation you will have *allure* command available.
Read more about https://github.com/qameta/homebrew-allure[Allure Homebrew Formula].

=== Debian
For Debian-based repositories we provide a PPA so the installation is straightforward:

[source,bash]
----
$ sudo apt-add-repository ppa:yandex-qatools/allure-framework
$ sudo apt-get update
$ sudo apt-get install allure-commandline
----

Supported distributions are: http://releases.ubuntu.com/14.04[Trusty] and http://releases.ubuntu.com/12.04[Precise].
After installation you will have allure command available.
Read more about https://github.com/allure-framework/allure-debian[Allure Debian Package].

=== Windows and other Unix
* Download the latest version as zip archive from link:https://bintray.com/qameta/generic/allure2[bintray].
* Unpack the archive to *allure-commandline* directory.
* Navigate to *bin* directory.
* Use *allure.bat* for Windows and *allure* for other Unix platforms.
* Add **allure** to system PATH.

== Configuration
To configure the Allure report you should create *allure.properties* file
[source]
.allure.properties
----
allure.issues.tracker.pattern=https://tms/testcase-%s
allure.tests.management.pattern=https://bugtracker/issue-%s
----

and simply generate the report. By default command line tool looking for config in directory you run the command.
**You can use ALLURE_CONFIG** environment variable to specify the path to configuration.

=== Usage
There is few commands available.

==== Generate the report
To generate the report from existing Allure results you can use the following command:

[source, bash]
----
$ allure generate directory-with-results/
----

The report will be generated to **allure-report** folder. You can change the destination folder using **-o** flag:
[source, bash]
----
$ allure generate directory-with-results/ -o directory-with-report
----

For more information use the *allure help generate* command.

=== Open the report
When the report is generated you can open it in your default system browser. Simply run
[source, bash]
----
$ allure report open
----

=== Clean the report
If you want to remove the generated report data use *allure report clean* command.

By default the report commands will looking for the report in *allure-results* folder.
If you are want to use the report from different location you can use *-o* option.