= Maven

This plugin generates Allure report by https://github.com/allure-framework/allure-core/wiki#gathering-information-about-tests[existing XML files] during the Maven build process.

== Installation
Add allure-maven-plugin to your pom.xml file build section.

[source, xml]
.pom.xml
----
<project>
    ...
    <plugin>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-maven</artifactId>
        <version>2.9</version>
    </plugin>
    ...
</project>
----

== Configuration
=== Properties handling

Since 2.5 report generation is configurable. There are a few ways to do it:

==== Directly from source code
Put **allure.properties** (**report.properties** for Allure 1.5 or above) to classpath.
Both compile *class* path and *test class* path are supported.

==== Or specify the *properties* in configuration
[[allure-maven-plugin-configuration]]
[source, xml, linenums]
.pom.xml
----
<plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <configuration>
       <properties>
           <allure.issues.tracker.pattern>http://example.com/%s</allure.issues.tracker.pattern>
       </properties>
    </configuration>
</plugin>
----

==== Or specify the *propertiesFilePath*
[source, xml, linenums]
.pom.xml
----
<configuration>
   <propertiesFilePath>path/to/your/allure.properties</propertiesFilePath>
</configuration>
----

=== Report version
Since 2.6, the plugin constructs a report using Allure which is downloaded from the default
https://dl.bintray.com/qameta/generic/io/qameta/allure/allure[url].
Allure is extracted and placed into the *.allure* folder created in your project directory.

The default Allure version is *2.0.1*
[source, xml, linenums]
.pom.xml
----
<configuration>
    <reportVersion>2.0.1</reportVersion>
</configuration>
----


You can specify your own url for the download, or you can specify a file path using the system property **allure.download.url**.
[source, xml, linenums]
.pom.xml
----
<configuration>
    <allureDownloadUrl>https://example.com/allure/allure-2.0.1.zip</allureDownloadUrl>
</configuration>
----

=== Results Directory
The path to Allure results directory. In general it is the directory created by allure adaptor and contains allure
files and attachments. This path can be relative from the build directory (for maven it is the target directory)
or absolute (absolute only for report mojo).

Default value is *"allure-results"*. 

System property **allure.results.directory**.
[source, xml, linenums]
.pom.xml
----
<configuration>
    <reportDirectory>allure-report</reportDirectory>
</configuration>
----

== Usage
You can generate a report using one of the following command:

* *mvn allure:serve*

Report will be generated into temp folder. Web server with results will start.

* *mvn allure:report*

Report will be generated tо directory: *target/site/allure-maven/index.html*