=== Maven

==== Installation
Add allure-maven-plugin to your pom.xml file.

[source, xml]
.pom.xml
----
<project>
    ...
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </reporting>
    ...
</project>
----

==== Configuration
===== Properties handling

Since 2.5 there is ability to configure report generation. There is few ways to do it:

====== Directly from source code
Put **allure.properties** (**report.properties** for Allure 1.5 or above) to classpath.
Both compile *class* path and *test class* path are supported.

====== Or specify the *properties* in configuration
[source, xml]
.pom.xml
----
<configuration>
   <properties>
       <allure.issues.tracker.pattern>http://example.com/%s</allure.issues.tracker.pattern>
   </properties>
</configuration>
----

====== Or specify the *propertiesFilePath*
[source, xml]
.pom.xml
----
<configuration>
   <propertiesFilePath>path/to/your/allure.properties</propertiesFilePath>
</configuration>
----

===== Results Directory
The path to Allure results directory. In general it is the directory created by allure adaptor and contains allure
xml files and attachments. This path can be relative from build directory (for maven it is the target directory)
or absolute (absolute only for report mojo). Will be ignored for bulk mojo.

Default value is *"allure-results"*. 

System property **allure.results.directory**.
[source, xml]
.pom.xml
----
<plugin>
    <groupId>ru.yandex.qatools.allure</groupId>
    <artifactId>allure-maven-plugin</artifactId>
    <configuration>
        <reportDirectory>allure-report</reportDirectory>
    </configuration>
</plugin>
----

==== Usage
The Allure Maven Plugin has three goals:

* *allure:report*
* *allure:aggregate*
* *allure:bulk*

===== Generate the Allure report as Part of Project Reports
[source, bash]
----
$ mvn site
----

===== Generate the Allure Report in a Standalone Fashion
The plugin can also generate the report using its standalone goal:
[source, bash]
----
$ mvn allure:report
----