= Cucumber JVM

== Installation

Each major version of Cucumber JVM requires a particular version of Allure Cucumber JVM adapter.

The available latest version of adapters:

- Cucumber JVM 1.x - `allure-cucumber-jvm` image:https://img.shields.io/maven-central/v/io.qameta.allure/allure-cucumber-jvm.svg[Allure Cucumber JVM 1.x]
- Cucumber JVM 2.x - `allure-cucumber2-jvm` image:https://img.shields.io/maven-central/v/io.qameta.allure/allure-cucumber2-jvm.svg[Allure Cucumber JVM 2.x]
- Cucumber JVM 3.x - `allure-cucumber3-jvm` image:https://img.shields.io/maven-central/v/io.qameta.allure/allure-cucumber3-jvm.svg[Allure Cucumber JVM 3.x]
- Cucumber JVM 4.x - `allure-cucumber4-jvm` image:https://img.shields.io/maven-central/v/io.qameta.allure/allure-cucumber4-jvm.svg[Allure Cucumber JVM 4.x]

=== Maven
Simply add `allure-cucumber4-jvm` plugin as a dependency to your project and add it to CucumberOptions:

[source, xml, linenums]
.pom.xml
----
<properties>
    <aspectj.version>1.8.10</aspectj.version>
</properties>

<dependencies>
    <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-cucumber4-jvm</artifactId>
        <version>LATEST_VERSION</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.20</version>
            <configuration>
                <argLine>
                    -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    -Dcucumber.options="--plugin io.qameta.allure.cucumber4jvm.AllureCucumber4Jvm"
                </argLine>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.aspectj</groupId>
                    <artifactId>aspectjweaver</artifactId>
                    <version>${aspectj.version}</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----

Then execute `mvn clean test` goal. After tests executed allure JSON files will be +
placed in `allure-results` directory by default.

=== Features
This adapter provides runtime integration allowing conversion of Gherkin dsl features into basic Allure features

=== Display Name
Titles for tests and suites are extracted at runtime from  `.feature` files

=== Description
Feature's description appears on every scenario

=== Steps
All scenario steps are automatically translated into allure steps

=== Attachments

include::../features/java-attachments.adoc[]

=== Links
To pass issues to report, just add `@issue=<ISSUE-NUMBER>` on top of Scenario on Feature in your .feature file.

To pass TMS links to report, just add `@tmsLink=<TEST-CASE-ID>` on top of Scenario on Feature in your .feature file.

NOTE: do not forget to configure allure properties with link patterns.

=== Severity
To set severity, add `@severity=blocker` on top of Scenario on Feature in your .feature file. +
If severity has wrong value it will be forced to normal (default).

Supported severity values: `blocker`, `critical`, `normal`, `minor`, `trivial`.

=== Test markers
Every Feature or Scenario can be annotated by following tags: `@flaky`, `@muted`, `@known`

=== Test fixtures
All methods annotated by `@import cucumber.api.java.After` or `@cucumber.api.java.Before` annotations +
will appear in the report as steps with method names. +
If @Before execution fails, the scenario will be marked as skipped. +
If @After execution fails, the scenario will be marked as passed, and only `After` method's step +
will be marked as failed.

=== Behaviours Mapping
Allure Cucumber JVM integration uses information extracted from `Feature:` section.

=== Configuration

include::../features/java-configuration.adoc[]
