= Glossary

Step:: An atomic test logic execution unit. Each test case can consist of one or more steps. Steps allow to divide
complex test cases into smaller pieces of logic. This can dramatically simplify analysis of test results because we
can determine which part of a test case caused the overall test case failure.

Attachment:: Any data (e.g. screenshot, log file, URL) that needs to be added to test results in order to clarify things.

Test:: A procedure, either manually executed or automated, that can be used to verify that the system under test (SUT)
is behaving as expected. Often called a test case.

Test case:: Usually a synonym for “test.” In xUnit, it may also refer to a testcase class, which is actually a test
suite factory as well as a place to put a set of related test methods.

Test fixture:: Everything a system under test needs to have in place so that we can exercise the SUT for the purpose
of verifying its behavior.

Test error:: When a test is run, an error that keeps the test from running to completion. The error may be explicitly
risen or thrown by the system under test (SUT) or by the test itself, or it may be thrown by the runtime system
(e.g., operating system or virtual machine). In general, it is much easier to debug a test error than a test failure,
because the root of the problem tends to be much more local to where the test error occurs.
Compare with test failure and test success.

Test failure:: When a test is run and the actual outcome does not match the expected outcome.
Compare with test error and test success.

Test result:: A test or test suite can be run many times, each time yielding a different test result.

Test run:: A test or test suite can be run many times, each time yielding a different test result. Some commercial test
automation tools record the results of each test run for prosperity.

Test success:: A situation in which a test is run and all actual outcomes match the expected outcomes. Compare with
test failure and test error.

Test suite:: A way to name a collection of tests that we want to run together.

Parameter:: Any data coming from outside allowing to clearly describe the test execution environment. For example,
this can be an operating system version or JDK release, or the exact URL of the software installation being tested.

Behavior-driven development:: A variation on the test-driven development process wherein the focus of the tests is to
clearly describe the expected behavior of the system under test (SUT). The emphasis is on Tests as Documentation rather
than merely using tests for verification.

Feature:: A testable unit of functionality that can be built onto the evolving software system.

Story:: The unit of incremental development in eXtreme Programming. A user story corresponds roughly to a “feature”
in non-eXtreme Programming terminology and is typically decomposed into one or more tasks to be carried out by project
team members.

System under test:: Whatever thing we are testing defined from the perspective of the test, e.g. method, class,
object or the entire application.