

name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kubeconfig
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show sites > $GITHUB_WORKSPACE/.kubeconfig
      - name: Deploy Chart
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            helmv3 repo add allure ${{ secrets.HELM_CHART_URL }}
            helmv3 upgrade allure-docs allure/site \
                   --values $GITHUB_WORKSPACE/chart/config.yml \
                   --kubeconfig $GITHUB_WORKSPACE/.kubeconfig \
                   --set image.tag=${{ github.event.inputs.version }} \
                   --install
