name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install
      - name: Install Gatsby
        run: npm install -g gatsby-cli
      - name: Build Gatsby
        run: gatsby build --prefix-paths
      - name: Build Version
        run: echo "SITE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/allure-framework/allure-docs:${{ env.SITE_VERSION }}
