name: Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: echo "::set-output name=version::${GITHUB_REF:10}"
        id: release
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          cache: 'yarn'
      - name: Install Deps
        run: yarn install
      - name: Install Gatsby
        run: npm install -g gatsby-cli
      - name: Build Gatsby
        run: gatsby build
      - name: Docker Publish
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repository: allure-framework/allure-docs
          tags: 1.0
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}
